export const example1 = {
  deiceStatus: 0,
  operationStatus: 1,
  modelSeriesSelection: 2,
  multiOdConnection: 0,
  specialStatus: [
    { specialMode: 1, operationStatus: 0 },
    { specialMode: 2, operationStatus: 0 },
  ],
  waterPressure: '0.00',
  cnCntErrorStatus: 0,
  zoneStatus: [
    {
      operationStatus: 1,
      ecoHeat: -5,
      coolMin: -5,
      heatMin: -5,
      comfortCool: -5,
      temparatureNow: 20,
      coolSet: -1,
      zoneId: 1,
      comfortHeat: 5,
      heatMax: 5,
      coolMax: 5,
      ecoCool: 5,
      heatSet: -5,
    },
    {
      operationStatus: 0,
      ecoHeat: 0,
      coolMin: null,
      heatMin: null,
      comfortCool: 0,
      temparatureNow: null,
      coolSet: 0,
      zoneId: 2,
      comfortHeat: 0,
      heatMax: null,
      coolMax: null,
      ecoCool: 0,
      heatSet: 0,
    },
  ],
  outdoorNow: 22,
  operationMode: 1,
  holidayTimer: 0,
  powerful: 0,
  electricAnode: null,
  deviceGuid: '',
  bivalent: 0,
  tankStatus: [
    {
      operationStatus: 1,
      temparatureNow: 50,
      heatMax: 65,
      heatMin: 40,
      heatSet: 52,
    },
  ],
  informationMessage: 1,
  pumpDuty: 0,
  quietMode: 0,
  forceHeater: 0,
  tank: 1,
  forceDHW: 0,
  pendingUser: 0,
  direction: 2,
};